/**
 * A connection which is generated by the server when processes the incoming request
 */
export default class Connection {
  /**
   * Constructor
   * @param {Request} request An object which is an instance of http/Request
   * @param {Response} response An object which is an instance of http/Response
   * @param {Server} server An instance of http/Server
   */
  constructor(request = null, response = null, server = null) {
    this.request  = request
    this.response = response
    this.server   = server
  }
}