/**
 * A connection which is generated by the server when processes the incoming request
 */
export default class Connection {
  /**
   * Constructor
   * @param {?Request} [request=null] An object which is an instance of http/Request
   * @param {?Response} [response=null] An object which is an instance of http/Response
   * @param {?Server} [server=null] An instance of http/Server
   */
  constructor(request = null, response = null, server = null) {
    /**
     * @type {Request}
     */
    this.request  = request

    /**
     * @type {Response}
     */
    this.response = response

    /**
     * @type {Server}
     */
    this.server   = server
  }
}
